#!/usr/bin/env python3
"""Generate docs/MEASURED_FINDINGS.md from artifacts/data_quality_report.json (+ optional manifest)."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--root", type=Path, default=None)
    args = p.parse_args()
    root = args.root or Path(__file__).resolve().parents[1]
    qa_path = root / "artifacts" / "data_quality_report.json"
    man_path = root / "artifacts" / "data_manifest.json"
    out_path = root / "docs" / "MEASURED_FINDINGS.md"

    if not qa_path.is_file():
        print(f"Missing {qa_path}; run prepare + data_quality_report first.", file=sys.stderr)
        return 1

    qa = json.loads(qa_path.read_text(encoding="utf-8"))
    manifest = json.loads(man_path.read_text(encoding="utf-8")) if man_path.is_file() else {}

    sft = qa.get("sft") or {}
    dpo = qa.get("dpo") or {}
    rid = manifest.get("recipe_id", "—")
    git = (manifest.get("environment") or {}).get("git_commit", "—")

    lines = [
        "# Measured findings (data plane)",
        "",
        "This file is **generated** from `artifacts/data_quality_report.json` after `prepare` + `data_quality_report`. "
        "Regenerate with:",
        "",
        "```bash",
        "python tools/prepare_data.py --root . --max-sft 2000 --max-dpo 2000   # or full export",
        "python tools/data_quality_report.py --root .",
        "python tools/render_measured_findings.py --root .",
        "python tools/plot_qa_figure.py --root .",
        "```",
        "",
        "## Scope of these numbers",
        "",
        "- They describe **exported JSONL** (after recipe filters), not raw Hub tables in full.",
        "- With default caps in the command above, rows are the **first** passing examples in dataset order — not a uniform subsample. "
        "For publication-style stats, export the full split or add explicit shuffling in `prepare_data.py`.",
        f"- **recipe_id:** `{rid}`",
        f"- **git_commit** (from manifest at export): `{git}`",
        "",
        "## SFT export (`repro_sft`)",
        "",
        f"- **rows:** {sft.get('rows')}",
        f"- **mean output chars:** {sft.get('output_char_len', {}).get('mean', 0):.2f}",
        f"- **p50 / p95 output chars:** {sft.get('output_char_len', {}).get('p50', 0):.1f} / {sft.get('output_char_len', {}).get('p95', 0):.1f}",
        f"- **approx. duplicate fraction (normalized hash):** {sft.get('approx_duplicate_fraction_sha256_norm_text', 0):.4f}",
        f"- **mean trigram repetition score (outputs):** {sft.get('output_trigram_repetition_mean', 0):.4f}",
        "",
        "### Interpretation",
        "",
        "- Near-zero **duplicate fraction** on this slice indicates Alpaca exports are diverse under the chosen normalization (not semantic dedup).",
        "- **Trigram repetition** is a cheap proxy for templated or looped text in `output`; unusually high values warrant spot-checking.",
        "",
        "## DPO export (`repro_dpo`, Ultrafeedback → flat pairs)",
        "",
        f"- **rows:** {dpo.get('rows')}",
        f"- **mean chosen / rejected chars:** {dpo.get('chosen_char_len', {}).get('mean', 0):.2f} / {dpo.get('rejected_char_len', {}).get('mean', 0):.2f}",
        f"- **p50 length delta (chosen − rejected):** {dpo.get('len_diff_chosen_minus_rejected', {}).get('p50', 0):.1f}",
        f"- **fraction chosen longer than rejected:** {dpo.get('fraction_chosen_longer_than_rejected', 0):.3f}",
        f"- **fraction with full shared prefix (up to shorter length):** {dpo.get('fraction_shared_prefix_all_chars_of_shorter', 0):.4f}",
        f"- **approx. duplicate fraction:** {dpo.get('approx_duplicate_fraction_sha256_norm_text', 0):.4f}",
        "",
        "### Interpretation",
        "",
        "- **Chosen longer than rejected** ~>0.5 is common in helpfulness-style prefs but is **not** a quality guarantee — length can correlate with hedging.",
        "- **Shared-prefix rate** near zero here suggests many pairs diverge early (different assistant continuations from the same user prompt) — "
        "consistent with how Ultrafeedback binarized pairs are structured after our last-assistant extraction.",
        "",
        "## Figure",
        "",
        "See [`docs/figures/data_qa_overview.svg`](figures/data_qa_overview.svg) (generated by `tools/plot_qa_figure.py`).",
        "",
        f"_`data_quality_report.created_at`: `{qa.get('created_at', '—')}`_",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


def cli() -> None:
    raise SystemExit(main())


if __name__ == "__main__":
    cli()
